name: onion_device_preview
description: "Miyoo Device Preview for OnionUI themes"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  dynamic_fonts: ^2.2.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true